name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: SveltyCMS Test
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [latest]
        pnpm-version: [latest]
        mongodb-version: [latest]
        test-file: ['/tests/signupfirstuser.spec.ts', '/tests/user.spec.ts']

    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Cache pnpm dependencies and Playwright browsers
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./pnpm-cache
            ./node_modules/playwright
          key: ${{ runner.OS }}-pnpm-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-playwright-
        # Continue workflow even if cache is not found
        continue-on-error: true

      - name: Install Node.js ${{ matrix.node-version }} and pnpm ${{ matrix.pnpm-version }}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        id: mongodb
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: SveltyCMS
          mongodb-port: 27017
        if: ${{ github.event_name != 'pull_request' }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies & Build Languages
        id: install
        run: pnpm install

      - name: Install Playwright Browsers
        id: install-playwright
        run: npx playwright install --with-deps

      - name: Run local server
        run: pnpm run build && pnpm run preview &

      - name: Run Playwright tests
        run: |
          for file in ${{ matrix.test-file }}; do
            npx playwright test $file --workers 10 &
          done
          wait
        # run: bunx playwright test
        env:
          privateEnv.DB_HOST: mongodb://localhost:27017/?authSource=admin
          privateEnv.DB_NAME: SveltyCMS
          privateEnv.DB_USER: admin
          privateEnv.DB_PASSWORD: admin
          publicEnv.SITE_NAME: SveltyCMS
          publicEnv.HOST_DEV: http://localhost:5173
          publicEnv.HOST_PROD: http://localhost:4173
          publicEnv.AVAILABLE_SYSTEM_LANGUAGES: ''
          publicEnv.DEFAULT_CONTENT_LANGUAGES: '{ "en": "English", "de": "German" }'
          publicEnv.SEASONS: true
          publicEnv.PKG: '{ VERSION: pkg.version }'
          publicEnv.MEDIA_FOLDER: media
          publicEnv._MEDIASERVER_URL: ''
          publicEnv.MEDIA_OUTPUT_FORMAT: 'avif'
          publicEnv.IMAGE_SIZES: '{ "sm": 600, "md": 900, "lg": 1200 }'
          privateEnv.USE_GOOGLE_OAUTH: 'false'
          privateEnv.GOOGLE_API_KEY: ''
          privateEnv.GOOGLE_CLIENT_ID: ''
          privateEnv.GOOGLE_CLIENT_SECERT: ''
          privateEnv.TWITCH_TOKEN: ''
          privateEnv.TIKTOK_TOKEN: ''
          privateEnv.SMTP_HOST: ''
          privateEnv.SMTP_PORT: ''
          privateEnv.SMTP_PASSWORD: ''
          privateEnv.SMTP_EMAIL: 'test@example.com'
          privateEnv.PUBLIC_MAPBOX_API_TOKEN: ''
          privateEnv.SECRET_MAPBOX_API_TOKEN: ''
          privateEnv.VITE_OPEN_AI_KEY: ''
          # Add more environment variables as needed...

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
