name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: SimpleCMS Test
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]
        pnpm-version: [latest]
        bun-version: [latest]
        mongodb-version: [latest]

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install Bun ${{ matrix.bun-version }}
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: ${{ matrix.bun-version }}

      # - name: Install pnpm ${{ matrix.pnpm-version }}
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: ${{ matrix.pnpm-version }}
      #     run_install: false

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: SimpleCMS
          mongodb-port: 27017

      - name: Install dependencies
        run: npm install
        # run: pnpm install
        # run: bun install

      - name: Build Languages
        run: npm run inlang
        # run: pnpm inlang
        # run: bun inlang

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        # run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        # run: bunx playwright test
        env:
          # BASE_URL: http://localhost:5173/
          DB_HOST: mongodb://localhost:27017/?authSource=admin
          DB_NAME: SimpleCMS
          DB_USER: admin
          DB_PASSWORD: admin
          PUBLIC_SITENAME: SimpleCMS
          HOST_DEV: http://localhost:5173
          HOST_PROD: http://localhost:4173
          PUBLIC_AVAILABLE_SYSTEMLANGUAGES: ''
          PUBLIC_CONTENT_LANGUAGES: '{ "en": "English", "de": "German" }'
          PUBLIC_PKG: '{ VERSION: pkg.version }'
          PUBLIC_MEDIA_FOLDER: media
          PUBLIC_MEDIASERVER_URL: ''
          PUBLIC_MEDIA_OUTPUT_FORMAT: 'avif'
          PUBLIC_IMAGE_SIZES: '{ "sm": 600, "md": 900, "lg": 1200 }'
          PUBLIC_USE_GOOGLE_OAUTH: 'false'
          SECRET_GOOGLE_API_KEY: ''
          SECRET_GOOGLE_CLIENT_ID: ''
          SECRET_GOOGLE_CLIENT_SECERT: ''
          SECRET_TWITCH_TOKEN: ''
          SECRET_TIKTOK_TOKEN: ''
          SMTP_HOST: ''
          SMTP_PORT: ''
          SMTP_PASSWORD: ''
          SMTP_EMAIL: 'test@example.com'
          PUBLIC_MAPBOX_API_TOKEN: ''
          SECRET_MAPBOX_API_TOKEN: ''
          VITE_OPEN_AI_KEY: ''
          # Add more environment variables as needed...

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
