name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: ['6.0']
        node-version: ['20']

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017
        env:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install && npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          DB_HOST: mongodb://localhost:27017/?authSource=admin
          DB_NAME: SimpleCMS
          DB_USER: admin
          DB_PASSWORD: admin
          PUBLIC_SITENAME: SimpleCMS
          HOST_DEV: http://localhost:5173
          HOST_PROD: https://localhost:4173
          PUBLIC_SYSTEM_LANGUAGE: en
          PUBLIC_CONTENT_LANGUAGES: '{ "en": "English", "de": "German" }'
          PUBLIC_PKG: '{ VERSION: pkg.version }'
          PUBLIC_MEDIA_FOLDER: mediaFiles
          PUBLIC_MEDIASERVER_URL: ''
          PUBLIC_MEDIA_OUTPUT_FORMAT: 'avif'
          PUBLIC_IMAGE_SIZES: '{ "sm": 600, "md": 900, "lg": 1200 }'
          # Add more environment variables as needed...

        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
